CREATE DATABASE IF NOT EXISTS nitro_legends CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE nitro_legends;

CREATE TABLE IF NOT EXISTS player_states (
    player_id VARCHAR(120) PRIMARY KEY,
    pos_x DECIMAL(10,3) NOT NULL DEFAULT 0,
    pos_y DECIMAL(10,3) NOT NULL DEFAULT 1.2,
    pos_z DECIMAL(10,3) NOT NULL DEFAULT 0,
    rot_y DECIMAL(10,3) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
